# Generated by Django 5.2 on 2025-04-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField()),
                ('em_stock', models.BooleanField(default=True)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.categoria')),
            ],
        ),
    ]
