# Generated by Django 5.2 on 2025-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_produtodestaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
