# Generated by Django 5.2 on 2025-04-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_produto_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtodestaque',
            options={'ordering': ['ordem'], 'verbose_name': 'Produto em Destaque', 'verbose_name_plural': 'Produtos em Destaque'},
        ),
        migrations.AlterField(
            model_name='produtodestaque',
            name='produto',
            field=models.ForeignKey(limit_choices_to={'favorito': True}, on_delete=django.db.models.deletion.CASCADE, to='website.produto'),
        ),
    ]
