# Generated by Django 5.2 on 2025-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_categoria_nome_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtodestaque',
            name='ordem',
            field=models.PositiveIntegerField(choices=[(1, '1ª posição'), (2, '2ª posição'), (3, '3ª posição')], unique=True),
        ),
    ]
