# Generated by Django 5.2 on 2025-04-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_parceiros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('imagem', models.ImageField(upload_to='parceiros/')),
                ('url', models.URLField(blank=True, null=True)),
                ('principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Parceiros',
        ),
    ]
