# Generated by Django 5.2 on 2025-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_parceiro_delete_parceiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='principal',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='parceiro',
            constraint=models.UniqueConstraint(fields=('principal',), name='unique_parceiro_principal'),
        ),
    ]
